name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo install cargo-tarpaulin      
    - run: cargo clippy
    - run: cargo test
    - run: cargo build --release
    - run: cargo tarpaulin --out Xml  
    - uses: codecov/codecov-action@v2
